### ISSUE TITLE
Loading BRITE as a CV: issues

### ISSUE THREAD

**Issue by bradfordcondon** [tripal/tripal_analysis_kegg#7]
Right now we plan to load the KEGG/BRITE terms as a CV.

There are a couple of issues.  Look at the root pathway map[here as json](http://www.genome.jp/kegg-bin/download_htext?htext=br08901.keg&format=json&filedir=) [here as html](http://www.genome.jp/kegg-bin/get_htext?br08901)

```
{
    "name":"br08901",
    "children":[
    {
        "name":"Metabolism",
        "children":[
        {
            "name":"Global and overview maps",
            "children":[
            {
                "name":"01100  Metabolic pathways"
            },
            }
```

Only the child nodes have accessions, and they correspond to BRITE pathways: for example, Metablic pathways is here http://www.genome.jp/kegg-bin/show_pathway?map01100

what to do about the intermediate nodes ie Metabolism?  It's a category that hte maps are in but is not a map itself and therefore has no accession in BRITE maps.

I'm not great with building ontologies, is there some correct way to add these accessionless terms that only have children?

**Comment by bradfordcondon** [comment]
@srobb1 your input in particular would be great if you have any ideas

**Comment by srobb1** [comment]
I think those terms without accessions are KEGG Orthology (KO) Terms and that they do actually have an ID. Maybe you can load up the KO terms, then search for the accession when loading the maps?

All the terms without accessions in your example json can be found here:
[KEGG Orthology](http://www.kegg.jp/kegg-bin/get_htext#A1)

[download json](http://www.kegg.jp/kegg-bin/download_htext?htext=ko00000.keg&format=json&filedir=)

[download htext](http://www.kegg.jp/kegg-bin/download_htext?htext=ko00000.keg&format=htext&filedir=)

Sofia

**Comment by bradfordcondon** [comment]
ah they are actually not KEGG terms but KEGG PATHWAY terms.

http://www.genome.jp/kegg/pathway.html#metabolism for example.

**Comment by srobb1** [comment]
So they area both KO and KEGG PATHWAY terms. Confusing.  

You can use words as accessions for an ontology terms.

**Comment by bradfordcondon** [comment]
so... do you think that the KEGG PATHWAY terms consist of a mixed CV, with both accession numbers (ie 01100 metabolic pathways) and words (ie 1.0 Global and overview maps) ?  The accessionless terms don't in turn correspond to pathway maps like [01100 does](http://www.genome.jp/kegg-bin/show_pathway?map01100)

**Comment by srobb1** [comment]
It certainly looks that way.

**Comment by spficklin** [comment]
Hey @bradfordcondon if you take a look at the old heir parse in the KEGG module you'll see that both pathways and orthologs get imported (although not in a heirarchy), so that code might help.  But in short, it looks to me like Orthologs are the leaf nodes of the JSON and always start with the letter K and pathways are internal nodes.  The term accession for the pathway is the number and the term name would be the text you reference, but without the preceeding number.  If you use this JSON I think it has it all:

http://www.genome.jp/kegg-bin/download_htext?htext=ko00000.keg&format=json&filedir=

This is awesome that you're working on this!   Are your plans to convert the JSON into OBO format and then load it up using the OBO loader?  Or where your plans to write a new parser for it?

**Comment by bradfordcondon** [comment]
No one in my group has much experience with OBO so our plan is to write a JSON-based parser, unfortunately.  And we're passing this off to a CS-based student so that's another point against an OBO approach.


What I'm learning is that BRITE is a mixed ontology.    It relates ENZYMES, PATHWAY/ORTHOLOGY, and MODULES to kegg terms, but it also has freetext terms that dont exist in those other CVs (for example, Metabolism).   e- metabolism does have an accession: `"09100 Metabolism"`.  trying to figure out if thats a BRITE accession or what....
 
So stephen I think that sometimes the internal nodes are pathways, but sometimes they are enzymes, sometimes they are modules, and sometimes they are just BRITE terms.  It seems like we need to load in all the CVs, and have some way to reference the other ones within BRITE.

I am keeping my notes understanding this here if you want to [peek](https://github.com/statonlab/hardwoods_site/issues/99).



edit- the solution im getting at is that we would have ONE CV- KEGG/BRITE.  Then each subset is loaded as a seperate DB.

The CV browser would operate on ko00000 that stephen linked to.  But kegg terms are inserted with DB: KEGG so that it can link out to the [kegg page](http://www.kegg.jp/dbget-bin/www_bget?ko:K19660), or the [module page](http://www.kegg.jp/kegg-bin/show_pathway?ko00053+K19660), as necessary. The urls here are really deceptive and each link is built differently.   


* http://www.kegg.jp/dbget-bin/www_bget?ko:K19660
http://www.kegg.jp/kegg-bin/show_pathway?ko00053

**Comment by srobb1** [comment]
Actually "Metabolism" is present in the ORTHOLOGY (KO). It is in the json that Stephen send: 

All the un-IDed terms might be KO terms.

```
{	
"name":"ko00000",
	"children":[
	{
		"name":"09100 Metabolism",
		"children":[
		{
			"name":"09101 Carbohydrate metabolism",
			"children":[
			{
				"name":"00010 Glycolysis \/ Gluconeogenesis [PATH:ko00010]",
				"children":[
```

**Comment by bradfordcondon** [comment]
that looks right to me.... but then the ko:09100 doesnt exist as a pathway :  http://www.kegg.jp/kegg-bin/show_pathway?ko09100

i guess thats denoted by the fact that there isnt a [PATH:ko00010] like there is for glycolysis in that example.

Can you find the corresponding entry on the kegg website that it would link out to?

**Comment by spficklin** [comment]
Hey @bradfordcondon OBO is really not that hard to generate, in our next meeting I can show you an example and it may actually save you time than trying to load the terms, setting relationships and properties. The OBO loader already does all of that and it has some extra add-ons such as importing to the cvtermpath table, and populating some mviews.

The current KEGG module loads three vocabularies:
KEGG_BRITE, KEGG_PATHWAYS and KEGG_ORTHOGS

You can see how the KEGG module loaded them on our demo site using the new vocabulary browser:
http://demo.tripal.info/3.x/cv/lookup/KEGG_BRITE
http://demo.tripal.info/3.x/cv/lookup/KEGG_ORTHOLOGY
http://demo.tripal.info/3.x/cv/lookup/KEGG_PATHWAY

The full vocabularies are not loaded, only those terms that were found in KEGG heir files  (which are now deprecated) from an analysis.

**Comment by spficklin** [comment]
Whether or not those are correct CV's I'm not 100% sure.  A second look at that might be a good idea.

**Comment by srobb1** [comment]
You asked about a URL for those terms using the ID. I can't find any. 

The only places I see those IDs are:

- http://www.genome.jp/kegg-bin/get_htext
- http://www.kegg.jp/kegg-bin/get_htext?ko00000.keg

Maybe the URLs you found are the only way to link to that Term http://www.genome.jp/kegg/pathway.html#metabolism 


I think that the Tripal 2 kegg loader (have not looked at the Trial 3 loader yet) only loaded the terms with accessions in the htext file, and did nothing with the terms with no accessions.

**Comment by bradfordcondon** [comment]
Thank you so much for confirming that, I was beginning to fear I was misunderstanding something....

That was what my original plan was: only load those with accessions and figure it out later.

Here's a crazy idea.  Load everything in as CV = BRITE/KEGG.  DB = depends on the term.  It will be either Orthology, pathway, map, etc... or **local** for accesionless BRITE terms.  

That way when this gets implemented with the cv-browser, you will properly link out to the right page on KEGG, but if you're a local term you go nowhere (or stay on site i guess).  The advantage is that this way we continue to keep those terms for the browser.

There might be a way that makes more sense loading in each BRITE subontology seperately, but right now in my muddled brain this is what i like

**Comment by spficklin** [comment]
Here are the URLs that I'm using to link to terms:

KEGG BRITE:  http://www.genome.jp/kegg-bin/get_htext?{accession}
KEGG ORTHOLOGY: http://www.genome.jp/dbget-bin/www_bget?{accession}
KEGG PATHWAY: http://www.genome.jp/dbget-bin/www_bget?{accession}

The current CV browser that we have in Tripal (just added this weekend) uses the database record as the starting point. This is because vocabularies such as the Gene Ontology have one database but several vocabularies (cellular_component. molecular_function and biological_process).  

Although this gets weird with the EDAM vocabulary because it does things the opposite way... It uses the vocabulary name to prefix the terms rather than the EDAM short name.   So, we have to store it in Chado backwards.

My vote would be to create a separate CV and DB for each KEGG vocabulary.  Since KEGG doesn't provide it's own OBO/OWL version (that I'm aware of) this seems like the simplest way to keep it all straight...

Perhaps it would be a good idea to reach out to KEGG and ask for clarification?

**Comment by bradfordcondon** [comment]
>Although this gets weird with the EDAM vocabulary because it does things the opposite way... It uses the vocabulary name to prefix the terms rather than the EDAM short name. So, we have to store it in Chado backwards.

this is pretty much why i proposed doing it this way: because we will end up wanting the accessions built based on hte db.  The one DB, many CV works when the accession is uniform (as is the case with go:  GO:0001 etc).  That's not the case here.

Creating separate CV/DB pairs for each will allow us to keep it all straight, and will seperate the ontologies in the browser.  I originally thought we wouldn't want this... but thinking about it, it wouldn't make a huge difference.

**Comment by spficklin** [comment]
I think it's okay.  In the current browser all the KEGG vocabularies lump together so they're easy to spot.  
http://demo.tripal.info/3.x/cv/lookup

Years ago someone did try to convert KEGG terms into an OBO.  We never used it because it wasn't well updated and now I can't find it.  

I wonder if KEGG has an OBO or OWL file behind their paid service. In which case, if they would allow us to use it then perhaps we could save some trouble.

**Comment by bradfordcondon** [comment]
probably no harm in asking.  I originally felt like we were taking lengths to avoid paying and felt bad asking.  But now we're just trying to add their ontology to our browser.

You have considerably more clout than me- would you be willing to ask?

**Comment by bradfordcondon** [comment]
Update:
@jwest60 Has created a script that parses the json into an OBO file.   
https://github.com/jwest60/tripal_analysis_kegg

Currently, the plan is this will create a single OBO file, with all KEGG terms loaded into a single CV/DB.  We are primarily concerned with the KO terms themselves (the leaf terms): this is what will link out only via the DB.

Other term types (ECC, pathway) are included with the term name == accession.  This is as opposed to loading in a seperate CV for each BRITE type.

Now that the ontology file is created, we are testing loading, and will build a loader that takes 2 columns: feature uniquename and KEGG term name, and annotates the features with the terms a la IPS/GO

**Comment by bradfordcondon** [comment]
Hi all,

Expect a pull request this week courtesy of @jwest60 's work.  We'll be adding:

* A PHP script that converts the KEGG Json definitions to OBO.
  - the OBO file has a single DB/CV entry.  Accesions are plain text for extra BRITE relationships (ECC, pathways etc) and True accession for Kegg Orthology terms.
* a new importer that just reads 2 column KEGG mappings (generated by KOALA)

This means the module will just read in terms and associate them with features.

**Comment by bradfordcondon** [comment]
our solution isnt perfect but it works.  thank you all in this thread for your helpful input.
